// <auto-generated />
namespace RedPetroleum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_displayName_TaskList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_displayName_TaskList));
        
        string IMigrationMetadata.Id
        {
            get { return "201807090456259_Add_displayName_TaskList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
