// <auto-generated />
namespace RedPetroleum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddtwotablesMarkandTaskMark : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddtwotablesMarkandTaskMark));
        
        string IMigrationMetadata.Id
        {
            get { return "201806251123474_Add two tables Mark and TaskMark"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
